name: "ci"

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: Build and Test
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
